version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      JWT_SECRET: Z4s&yH@3qP!t92fL^XvBd8MjKcW0RgTu
    volumes:
      - ./backend:/app
    command: npm start

volumes:
  mysql-data: